import { collectEnv } from './resolver.js';

// Strip CRs and expand {{BASE_URL}} to this platform's public URL so hosted
// binaries (e.g. the devsecops CLI) can be downloaded from generated scripts.
const esc = (s = '') => {
  const base = process.env.PUBLIC_BASE_URL || 'http://localhost:4000';
  return String(s).replace(/\r/g, '').replaceAll('{{BASE_URL}}', base);
};

function envBlock(env) {
  const keys = Object.keys(env);
  if (!keys.length) return '';
  let out = '\n# ---- Environment variables ----\n';
  for (const key of keys) {
    const meta = env[key] || {};
    const def = meta.default != null ? String(meta.default) : '';
    const label = (meta.prompt || `Enter ${key}`).replace(/"/g, '\\"');
    // Show the default inside the prompt: "Enter X [8000]: "
    const prompt = def ? `${label} [${def.replace(/"/g, '\\"')}]` : label;

    // Prompt whenever the var is required OR has a default to offer.
    if (meta.required || def) {
      out += `if [ -z "\${${key}:-}" ]; then\n`;
      out += `  read -r -p "${prompt}: " ${key}\n`;
      if (def) out += `  ${key}="\${${key}:-${def}}"\n`;
      out += `  export ${key}\n`;
      if (meta.required && !def) {
        out += `  if [ -z "\${${key}:-}" ]; then log_err "${key} is required"; exit 1; fi\n`;
      }
      out += `fi\n`;
    } else {
      out += `# optional: ${key}\n`;
    }
  }
  return out;
}

function defineStep(index, name, steps) {
  const detect = esc(steps.detect || '');
  const install = esc(steps.install || '');
  const verify = esc(steps.verify || '');
  const rollback = esc(steps.rollback || '');
  const config = esc(steps.config || '');

  let b = `\n# ===== Step ${index}: ${name} =====\n`;
  b += `step_${index}() {\n`;
  if (detect) {
    b += `  if ${detect} >/dev/null 2>&1; then log_ok "${name} already present, skipping"; return 0; fi\n`;
  }
  if (install) {
    b += `  log_info "Installing ${name}..."\n  ${install}\n`;
  }
  if (config) {
    b += `  log_info "Configuring ${name}..."\n  ${config}\n`;
  }
  if (verify) {
    b += `  if ! { ${verify}; } >/dev/null 2>&1; then log_err "${name} verify failed"; return 1; fi\n`;
  }
  b += `  log_ok "${name} done"; return 0\n}\n`;
  b += `rollback_${index}() {\n`;
  if (rollback) b += `  log_warn "Rolling back ${name}..."\n  ${rollback} || true\n`;
  else b += `  :\n`;
  b += `}\n`;
  return b;
}

export function generateBash({ manifest, resolved }) {
  const env = collectEnv(resolved);
  let s = '#!/usr/bin/env bash\n';
  s += `# Generated by Dev Bootstrap Platform\n`;
  s += `# Manifest: ${manifest.name} v${manifest.version}\n`;
  s += 'set -uo pipefail\n\n';

  s += 'C_GREEN="\\033[0;32m"; C_RED="\\033[0;31m"; C_YEL="\\033[0;33m"; C_BLU="\\033[0;34m"; C_RST="\\033[0m"\n';
  s += 'log_ok(){ printf "%b\\n" "${C_GREEN}\\xe2\\x9c\\x94 $*${C_RST}"; }\n';
  s += 'log_info(){ printf "%b\\n" "${C_BLU}\\xe2\\x86\\x92 $*${C_RST}"; }\n';
  s += 'log_warn(){ printf "%b\\n" "${C_YEL}\\xe2\\x9a\\xa0 $*${C_RST}"; }\n';
  s += 'log_err(){ printf "%b\\n" "${C_RED}\\xe2\\x9c\\x96 $*${C_RST}" 1>&2; }\n\n';

  s += 'run_step(){\n';
  s += '  local idx="$1" name="$2" fn="$3"\n';
  s += '  if ! "$fn"; then\n';
  s += '    log_err "Step $idx ($name) failed"\n';
  s += '    "rollback_$idx" 2>/dev/null || true\n';
  s += '    log_err "Aborting. Steps before $idx are kept."\n';
  s += '    exit 1\n';
  s += '  fi\n';
  s += '}\n';

  s += envBlock(env);
  s += `\nlog_info "Starting ${manifest.name} bootstrap..."\n`;

  resolved.forEach(({ module, version }, i) => {
    s += defineStep(i + 1, module.name, version.bash || {});
  });
  s += '\n';
  resolved.forEach(({ module }, i) => {
    s += `run_step "${i + 1}" "${module.name}" step_${i + 1}\n`;
  });

  s += '\nlog_ok "Done. Environment ready."\n';
  return s;
}
