import { collectEnv } from './resolver.js';

// Strip CRs and expand {{BASE_URL}} to this platform's public URL.
const esc = (s = '') => {
  const base = process.env.PUBLIC_BASE_URL || 'http://localhost:4000';
  return String(s).replace(/\r/g, '').replaceAll('{{BASE_URL}}', base);
};

function envBlock(env) {
  const keys = Object.keys(env);
  if (!keys.length) return '';
  let out = '\n# ---- Environment variables ----\n';
  for (const key of keys) {
    const meta = env[key] || {};
    const def = meta.default != null ? String(meta.default) : '';
    const label = (meta.prompt || `Enter ${key}`).replace(/"/g, '`"');
    const prompt = def ? `${label} [${def.replace(/"/g, '`"')}]` : label;

    if (meta.required || def) {
      out += `if (-not $env:${key}) {\n`;
      out += `  $env:${key} = Read-Host "${prompt}"\n`;
      if (def) out += `  if (-not $env:${key}) { $env:${key} = "${def.replace(/"/g, '`"')}" }\n`;
      if (meta.required && !def) {
        out += `  if (-not $env:${key}) { Log-Err "${key} is required"; exit 1 }\n`;
      }
      out += `}\n`;
    } else {
      out += `# optional: ${key}\n`;
    }
  }
  return out;
}

function defineStep(index, name, steps) {
  const detect = esc(steps.detect || '');
  const install = esc(steps.install || '');
  const verify = esc(steps.verify || '');
  const rollback = esc(steps.rollback || '');
  const config = esc(steps.config || '');

  let b = `\n# ===== Step ${index}: ${name} =====\n`;
  b += `function Step-${index} {\n`;
  if (detect) {
    // [bool] keeps the return value clean (no stray objects leaking out).
    b += `  if ([bool](${detect})) { Log-Ok "${name} already present, skipping"; return $true }\n`;
  }
  if (install) {
    // Run install in a child scope and send ALL streams to the host, so tool
    // stdout/stderr is shown+logged but never leaks into this function's return.
    b += `  Log-Info "Installing ${name}..."\n`;
    b += `  & { ${install} } *>&1 | Out-Host\n`;
    // Reload PATH so tools just installed become usable in this same session.
    b += `  Refresh-Path\n`;
  }
  if (config) {
    b += `  Log-Info "Configuring ${name}..."\n`;
    b += `  & { ${config} } *>&1 | Out-Host\n`;
  }
  if (verify) {
    b += `  if (-not [bool](${verify})) { Log-Err "${name} verify failed"; return $false }\n`;
  }
  b += `  Log-Ok "${name} done"; return $true\n}\n`;
  b += `function Rollback-${index} {\n`;
  if (rollback) b += `  Log-Warn "Rolling back ${name}..."\n  try { & { ${rollback} } *>&1 | Out-Host } catch { }\n`;
  else b += `  # no rollback\n`;
  b += `}\n`;
  return b;
}

export function generatePowershell({ manifest, resolved }) {
  const env = collectEnv(resolved);
  let s = `# Generated by Dev Bootstrap Platform\n`;
  s += `# Manifest: ${manifest.name} v${manifest.version}\n`;
  // Continue (not Stop): tools routinely write warnings to stderr (e.g. semgrep's
  // deprecation notices). With Stop those would be treated as terminating errors
  // and abort the run. Each step decides success/failure via its own `verify`.
  s += '$ErrorActionPreference = "Continue"\n\n';

  s += 'function Log-Ok($m){ Write-Host "[OK] $m" -ForegroundColor Green }\n';
  s += 'function Log-Info($m){ Write-Host "[..] $m" -ForegroundColor Cyan }\n';
  s += 'function Log-Warn($m){ Write-Host "[!!] $m" -ForegroundColor Yellow }\n';
  s += 'function Log-Err($m){ Write-Host "[XX] $m" -ForegroundColor Red }\n\n';

  // Log everything to a file so output survives even if the window closes.
  s += '$LogFile = Join-Path $env:TEMP ("devsecops-bootstrap-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".log")\n';
  s += 'try { Start-Transcript -Path $LogFile -Force | Out-Null } catch { }\n';
  s += 'Log-Info "Logging to $LogFile"\n\n';

  // Keep the window open so a fast failure/exit is readable. Skips the pause in
  // non-interactive contexts (e.g. CI) where no console is attached.
  s += 'function Pause-End($code){\n';
  s += '  try { Stop-Transcript | Out-Null } catch { }\n';
  s += '  if ([Environment]::UserInteractive -and $Host.Name -eq "ConsoleHost") {\n';
  s += '    Write-Host ""\n';
  s += '    Write-Host "Log saved to: $LogFile" -ForegroundColor DarkGray\n';
  s += '    Read-Host "Press Enter to close"\n';
  s += '  }\n';
  s += '  exit $code\n';
  s += '}\n\n';

  // Merge the Machine + User PATH into the CURRENT session PATH (union, keeping
  // anything already added this session, e.g. pip Scripts). Freshly installed
  // tools become usable without dropping session-local entries.
  s += 'function Refresh-Path {\n';
  s += '  $m = [Environment]::GetEnvironmentVariable("PATH","Machine")\n';
  s += '  $u = [Environment]::GetEnvironmentVariable("PATH","User")\n';
  s += '  $seen = @{}; $out = @()\n';
  s += '  foreach ($part in (($env:PATH, $m, $u) -join ";").Split(";")) {\n';
  s += '    if ($part -and -not $seen.ContainsKey($part)) { $seen[$part] = $true; $out += $part }\n';
  s += '  }\n';
  s += '  $env:PATH = $out -join ";"\n';
  s += '}\n\n';

  // Find a REAL python, skipping the Microsoft Store "App execution alias" stub
  // (WindowsApps\python.exe) that pretends to exist but errors on use. Also looks
  // in the common install dirs, because Python installed without "Add to PATH"
  // won't be on PATH at all (only the stub is). Returns an absolute path or $null.
  s += 'function Get-RealPython {\n';
  s += '  $cands = @()\n';
  // 1) whatever is on PATH, minus the WindowsApps stub
  s += '  foreach ($n in @("python","python3")) {\n';
  s += '    $cands += (Get-Command $n -All -ErrorAction SilentlyContinue | \n';
  s += '      Where-Object { $_.Source -and $_.Source -notlike "*WindowsApps*" } | \n';
  s += '      Select-Object -ExpandProperty Source)\n';
  s += '  }\n';
  // 2) the py launcher can tell us the real exe
  s += '  $pyl = Get-Command py -ErrorAction SilentlyContinue\n';
  s += '  if ($pyl) {\n';
  s += '    try { $pp = (& $pyl.Source -3 -c "import sys;print(sys.executable)" 2>$null); if ($pp) { $cands += $pp } } catch { }\n';
  s += '  }\n';
  // 3) common install locations (installed without "Add to PATH")
  s += '  $dirs = @("$env:LOCALAPPDATA\\Programs\\Python", "$env:ProgramFiles", "${env:ProgramFiles(x86)}", "C:\\")\n';
  s += '  foreach ($d in $dirs) {\n';
  s += '    Get-ChildItem -Path $d -Directory -Filter "Python3*" -ErrorAction SilentlyContinue | ForEach-Object {\n';
  s += '      $e = Join-Path $_.FullName "python.exe"; if (Test-Path $e) { $cands += $e }\n';
  s += '    }\n';
  s += '  }\n';
  // pick the first candidate that actually runs and reports Python 3
  s += '  foreach ($src in ($cands | Select-Object -Unique)) {\n';
  s += '    try { $v = & $src --version 2>&1; if ($LASTEXITCODE -eq 0 -and "$v" -match "Python 3") { return $src } } catch { }\n';
  s += '  }\n';
  s += '  return $null\n';
  s += '}\n\n';

  // Return a working python path, installing Python 3 (user scope) if needed.
  s += 'function Ensure-Python {\n';
  s += '  $p = Get-RealPython\n';
  s += '  if ($p) { return $p }\n';
  s += '  Log-Info "Python not found, installing Python 3..."\n';
  s += '  winget install --id Python.Python.3.12 -e --scope user --accept-source-agreements --accept-package-agreements | Out-Null\n';
  s += '  Refresh-Path\n';
  s += '  $p = Get-RealPython\n';
  s += '  if (-not $p) { throw "Python installed but not on PATH yet. Open a NEW terminal and re-run this installer." }\n';
  s += '  return $p\n';
  s += '}\n\n';

  // Ensure pip's user Scripts dir (where semgrep.exe / checkov.exe land) is on
  // PATH — both for THIS session and persisted to the User PATH so the tools are
  // callable later (e.g. when `devsecops scan` shells out to them).
  s += 'function Add-UserScripts {\n';
  s += '  $p = Get-RealPython\n';
  s += '  if (-not $p) { return }\n';
  s += '  try {\n';
  s += "    $sc = (& $p -c \"import sysconfig;print(sysconfig.get_path('scripts','nt_user'))\" 2>$null)\n";
  s += '    if (-not $sc) { return }\n';
  s += '    if (-not (Test-Path $sc)) { return }\n';
  s += '    if (($env:PATH -split ";") -notcontains $sc) { $env:PATH = "$sc;$env:PATH" }\n';
  s += '    $userPath = [Environment]::GetEnvironmentVariable("PATH","User")\n';
  s += '    if (($userPath -split ";") -notcontains $sc) {\n';
  s += '      [Environment]::SetEnvironmentVariable("PATH", "$sc;$userPath", "User")\n';
  s += '      Log-Info "Added $sc to your PATH"\n';
  s += '    }\n';
  s += '  } catch { }\n';
  s += '}\n\n';

  // True if a pip package is installed. Uses `pip show` (metadata only) rather
  // than running the tool, so deprecation warnings never trip us up.
  s += 'function Test-PipPackage($pkg) {\n';
  s += '  $p = Get-RealPython\n';
  s += '  if (-not $p) { return $false }\n';
  s += '  $out = & $p -m pip show $pkg 2>$null\n';
  s += '  return [bool]($out)\n';
  s += '}\n\n';

  s += 'function Run-Step($idx, $name, $stepFn, $rollbackFn){\n';
  s += '  $ok = & $stepFn\n';
  s += '  if (-not $ok) {\n';
  s += '    Log-Err "Step $idx ($name) failed"\n';
  s += '    try { & $rollbackFn } catch { }\n';
  s += '    Log-Err "Aborting. Steps before $idx are kept."\n';
  s += '    Pause-End 1\n';
  s += '  }\n';
  s += '}\n';

  s += envBlock(env);
  // Sync PATH once up front: if this shell started before a previous install,
  // its PATH is stale and detect checks would miss already-installed tools.
  s += '\nRefresh-Path\n';
  s += `Log-Info "Starting ${manifest.name} bootstrap..."\n`;

  resolved.forEach(({ module, version }, i) => {
    s += defineStep(i + 1, module.name, version.powershell || {});
  });
  s += '\n';
  // Run steps inside try/catch so an unexpected error also pauses instead of
  // slamming the window shut.
  s += 'try {\n';
  resolved.forEach(({ module }, i) => {
    const idx = i + 1;
    s += `  Run-Step ${idx} "${module.name}" \${function:Step-${idx}} \${function:Rollback-${idx}}\n`;
  });
  s += '  Log-Ok "Done. Environment ready."\n';
  s += '  Pause-End 0\n';
  s += '} catch {\n';
  s += '  Log-Err ("Unexpected error: " + $_.Exception.Message)\n';
  s += '  Log-Err $_.ScriptStackTrace\n';
  s += '  Pause-End 1\n';
  s += '}\n';
  return s;
}

